// Request
export const CREATE_REQUEST = 'CREATE_REQUEST';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';

// Entries
export const SET_LEFT_RIGHT_ENTRIES = 'SET_LEFT_RIGHT_ENTRIES';
export const CAN_VOTE = 'CAN_VOTE';
